<nav>
  <div class="d-flex">
    <div class="dropdown mr-1">
      <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20"> menu
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
        <a class="dropdown-item" href="/admin">Accueil</a>
        <a class="dropdown-item" href="/user">Mes adhérants</a>
        <a class="dropdown-item" href="/information">Mes informations</a>
        <a class="dropdown-item" href="/parametres">Mes parametres</a>
        <?php if ($this->session->get('fonction')=="super-admin"){?> <a class="dropdown-item" href="/admin/utilisateurs">Utilisateur</a><?php }?>
      </div>
    </div>
  </div>
</nav>
<section>
  <h1 style="display:none">Formulaire</h1>
  <?= $this->tag->form(['admin/modification', 'method' =>'post', 'enctype'=> "multipart/form-data"]); ?>
    <label>NOM :</label>
    <?= $this->tag->textField(
      [
        "nom",
        "value" =>$modifier->getNom()
      ]
    );?>
    <label>PRENOM :</label>
    <?= $this->tag->textField(
      [
        "prenom",
        "value" =>$modifier->getPrenom()
      ]
    );?>
    <label>IDENTIFIANT :</label>
    <?= $this->tag->textField(
      [
        "identifiant",
        "value" =>$modifier->getIdentifiant()
      ]
    );?>
    <label>MOT DE PASSE :</label>
    <?= $this->tag->passwordField(
      [
        "mdp",
        "value" => "******"
      ]
    );?>
    <?= $this->tag->hiddenField(
      [
        "id",
        "value" => $modifier->getId()
      ]
    );?>

    <?= $this->tag->submitButton(
      [
        "envoyer",
        "class" => "btn btn_primary"
      ]
    )?>
  <?= $this->tag->endForm();?>
  <a href="/user/index"  class="retour"> <button type="button" class="btn btn-primary" >retour</button> </a>
</section>