<?php $this->assets->outputCss(); ?>
<?php $this->assets->outputCss(); ?>
<div class="d-flex">
  <div class="dropdown mr-1">
    <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20">menu
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
      <a class="dropdown-item" href="/admin">Accueil</a><br>
      <a class="dropdown-item" href="/user">Mes adhérants</a><br>
      <a class="dropdown-item" href="/information">Mes informations</a><br>
      <a class="dropdown-item" href="/parametres">Mes parametres</a><br>
      <?php if ($this->session->get('fonction')=="super-admin"){?> <a class="dropdown-item" href="/admin/utilisateurs">Utilisateur</a><?php }?>
    </div>
  </div>
</div>
<a href="add">ajouter</a>
<table class="display" id="myTable">
  <thead>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Identifiant</th>
    <th>Mot de passe</th>
    <th>Modifier</th>
    <th>Supprimer</th>
  </thead>
  <tbody>  
<?php 
foreach ($utilisateurs as $utilisateur){ ?>
  <tr>
    <td><?php echo $utilisateur->getNom();?></td>
    <td><?php echo $utilisateur->getPrenom();?></td>
    <td><?php echo $utilisateur->getIdentifiant();?></td>
    <td>******</td>
    <td><a href="modifier?id=<?php echo $utilisateur->getId();?>">mod</a></td>
    <td><a href="delete?id=<?php echo $utilisateur->getId();?>">supp</a></td>
  </tr>

  <?php
} ?>
  </tbody>
</table>