<!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css"><font></font> -->
<!-- <font></font> -->
<!-- <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script><font></font> -->
<?php $this->assets->outputCss(); ?>

<!-- <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"> -->
<div class="d-flex">
  <div class="dropdown mr-1" id="menu">
    <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false" data-offset="10,20">menu
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
      <a class="dropdown-item" href="/admin">Accueil</a><br>
      <a class="dropdown-item" href="/user">Mes adhérants</a><br>
      <a class="dropdown-item" href="/information">Mes informations</a><br>
      <a class="dropdown-item" href="/parametres">Mes parametres</a><br>
      <?php if ($this->session->get('fonction')=="super-admin"){?> <a class="dropdown-item" href="/admin/utilisateurs">Utilisateur</a><?php }?>
    </div>
  </div>
</div>
<table class="table table-striped table-bordered" id="myTable">
  <thead>
    <th>Nom</th>
    <th>Prénom</th>
    <th>Adresse</th>
    <th>Code postal</th>
    <th>Ville</th>
    <th>Sexe</th>
    <th>Date de naissance</th>
    <th>Catégorie</th>
    <th>N° de téléphone portable</th>
    <th>N° de téléphone fixe</th>
    <th>Mail</th>
    <th>Taille</th>
    <th>Modifier</th>
    <th>Supprimer</th>
    <th></th>

  </thead>
  <tbody>
    <a href="/user/deleteall">delete all</a>
    <?php
        foreach ($users as $user) {
            ?>
    <tr>
      <td><?php echo $user->getLastname(); ?>
      </td>
      <td><?php echo $user->getFirstname(); ?>
      </td>
      <td><?php echo $user->getAddress(); ?>
      </td>
      <td><?php echo $user->getPostalCode(); ?>
      </td>
      <td><?php echo $user->getCity(); ?>
      </td>
      <td><?php echo $user->getSexe(); ?>
      </td>
      <?php $birthdateFr = date("d-m-Y", strtotime($user->getBirthdate())); ?>
      <td><?php echo $birthdateFr ; ?>
      </td>
      <td><?php echo $user->getCategorie(); ?>
      
      
      <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#categories<?php echo $user->getId(); ?>">
          modifier
        </button>
        <!-- Modal -->
        <div class="modal fade" id="categories<?php echo $user->getId(); ?>"
          tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Catégories</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <!-- <span aria-hidden="true">&times;</span> -->
                  <span aria-hidden="true">X</span>
                </button>
              </div>
              <div class="modal-body">
                <?=  $this->tag->form(['user/modifcategorie', 'method' =>'post', ]); ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U7",
                    ]
                  ); ?>
                <label for="U7">U7</label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" =>"U9",
                    ]
                  ); ?>
                <label for="U9">U9</label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U11",
                    ]
                  ); ?>
                <label for="U11">U11</label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U13",
                    ]
                  ); ?>
                <label for="U13">U13 </label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U15",
                    ]
                  )?>
                <label for="U15">U15 </label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U17",
                    ]
                  )?>
                <label for="U17"> U17 </label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U18",
                    ]
                  )?>
                <label for="U18">U18 </label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "U20",
                    ]
                  )?>
                <label for="U20">U20 </label>
                <?php echo "<br>"; ?>
                <?= $this->tag->checkField(
                    [
                      "categorie[]",
                      "value" => "SENIOR",
                    ]
                  )?>
                <label for="SENIOR">SENIOR</label>
                <?php echo "<br>";
            $equipes = Equipes::find();
            foreach ($equipes as $equipe) {
                ?>
                <?= $this->tag->checkField(
                      [
                        "categorie[]",
                        "value" => $equipe->name,
                      ]
                    );
                echo $equipe->name; ?>
                <a href="equipe/delete?id=<?php echo$equipe->id; ?>">x</a>
                <?php echo "<br>";
            } ?>
                <?= $this->tag->hiddenField(
                    [
                      "id",
                      "value" => $user->getId()
                    ]
                  ); ?>
                <?= $this->tag->submitButton(
                    [
                      "modifier",
                      "class" => "btn btn_primary"
                    ]
                  )?>
                <?= $this->tag->endForm(); ?>

              </div>
              <div class="modal-footer">
                <h6>Ajouter une équipe</h6>
                <?= $this->tag->form(['equipe/newequipe', 'method' =>'post']); ?>
                <label for="equipes">Nom de l'équipe : </label>
                <?= $this->tag->textField(
                    [
                      "nom"
                    ]
                  ); ?>
                <?= $this->tag->submitButton(
                    [
                      "envoyer",
                      "class" => "btn btn_primary"
                    ]
                  )?>
                <?= $this->tag->endForm(); ?>
                <!--   <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermé</button>
                <button type="button" class="btn btn-primary">Save changes</button> -->
              </div>
            </div>
          </div>
      </td>
      <td><?php echo $user->getPhoneNumber(); ?>
      </td>
      <td><?php echo $user->getFixNumber(); ?>
      </td>
      <td><?php echo $user->getMail(); ?>
      </td>
      <td><?php echo $user->getTaille(); ?>
      </td>
      <td><a href="/user/update?id=<?php echo $user->getID(); ?>"><img
            src="/<?php echo($_SESSION['URL']);?>/public/img/modif.png"></a></td>
      <td><a href="/user/delete?id=<?php echo $user->getID(); ?>"><img
            src="/<?php echo($_SESSION['URL']);?>/public/img/supprimer.png"></a></td>
      <td>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter<?php echo $user->getId(); ?>">
          Voir plus
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter<?php echo $user->getId(); ?>"
          tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Informations supplémentaires</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <?php if ($user->getParents()) {
                      ?>
                <h5>PARENTS</h5>
                <h6>PERE : </h6>
                <div class="fields"> NOM :
                  <?php
                        $parents = $user->getParents();
                      echo $parents->getNomDuPere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> PRENOM :
                  <?php
                        echo $parents->getPrenomDuPere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> MAIL :
                  <?php
                        echo $parents->getMailDuPere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> PROFESSION :
                  <?php
                        echo $parents->getProfessionDuPere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> ENTREPRISE :
                  <?php
                        echo $parents->getEntrepriseDuPere();
                      echo "<br>"; ?>
                </div>
                <h6>MERE : </h6>
                <div class="fields"> NOM :
                  <?php
                        echo $parents->getNomDeLaMere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> PRENOM :
                  <?php
                        echo $parents->getPrenomDeLaMere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> MAIL :
                  <?php
                        echo $parents->getMailDeLaMere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> PROFESSION :
                  <?php
                        echo $parents->getProfessionDeLaMere();
                      echo "<br>"; ?>
                </div>
                <div class="fields"> ENTREPRISE :
                  <?php
                        echo $parents->getEntrepriseDeLaMere();
                      echo "<br>"; ?>
                </div>
                <?php
                  } ?>

                <h5>MEDICAL</h5>
                <?php
                    if ($user->getMedical()) {
                        $medical = $user->getMedical(); ?>
                <div class="fields"> NOM :
                  <?php
                          echo $medical->getFirstname();
                        echo "<br>"; ?>
                </div>
                <div class="fields"> PRENOM :
                  <?php
                          echo $medical->getLastname();
                        echo "<br>"; ?>
                </div>
                <div class="fields"> N°de téléphone :
                  <?php
                          echo $medical->getPhoneNumber();
                        echo "<br>"; ?>
                </div>
                <div class="fields"> QUALITÉ :
                  <?php
                          echo $medical->getQuality();
                        echo "<br>"
                        ?>
                </div>
                <div class="fields"> PROBLEME MEDICAL :
                  <?php
                          echo $medical->getProbleme();
                        echo"<br>"; ?>
                </div>
                <?php
                    } ?>
                <h5>AUTORISATIONS</h5>
                <?php
                      if ($user->getAutorisation()) {
                          $autorisation = $user->getAutorisation(); ?>
                <div class="fields"> l'enfant est autorisé à quitter le gymnase seul :
                  <?php
                        echo $autorisation->getQuitterLeGymnase();
                          echo "<br>"; ?>
                </div>
                <div class="fields"> le club est autorisé à faire pratiquer tous actes médicaux dont la chirurgie si
                  cela est nécessaire :
                  <?php
                        echo $autorisation->getActesMedical();
                          echo "<br>"; ?>
                </div>
                <?php
                      } ?>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermé</button>
              </div>
            </div>
          </div>
        </div>
      </td>
      <?php
        } ?>
  </tbody>
</table>